### ISSUE TITLE
More intuitive name?

### ISSUE THREAD

**Issue by felixfbecker** [markwragg/PowerShell-Lumos#8]
`Invoke-Lumos` is a cool name, but it doesn't really describe what it does. In general, `Invoke` could be used to describe any cmdlet (e.g. `Invoke-Dir` instead of `Get-ChildItem`), but it is somewhat cheating the `Verb-Noun` convention. I think something like `Set-DarkMode`, `Set-ColorScheme` or `Enable-DarkMode` would be more intuitive.

**Comment by markwragg** [comment]
I struggled quite a lot with naming this one, and I agree its not necessarily ideal. I didn't want to have separate cmdlets for enabling dark and light mode, and I didn't think a name around something like Colour Scheme/Theme was necessarily accurate because in Windows at least Themes have existed for a long time and for the most part refer to something different.

I wanted a word that referred to the concept of dark and light as one, and the closest thing I could find was luminosity, with Lumos being a shorter version of that (plus being a bit of a geeky Harry Potter reference).

You're right using `Invoke-` is a bit of a cheat as well, but the reason for that is that the cmdlet by default will set either Dark or Light mode dependent on your location and time of day, so you are (by default) _invoking_ Lumos to make that determination and setting for you.

That being said it wouldn't be much effort to add something like `Set-DarkMode` as an alias or wrapper function. I wouldn't want to make a breaking change by renaming it at this point.
